/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#968e9c',
        'on-secondary': '#620044',
        'on-background': '#e1e2eb',
        'error-container': '#93000a',
        'tertiary-fixed': '#ffdcbc',
        'surface': '#10131a',
        'surface-container-highest': '#32353c',
        'primary-container': '#bd93f9',
        'surface-tint': '#d7baff',
        'on-error-container': '#ffdad6',
        'on-primary-container': '#4e2484',
        'on-tertiary-container': '#593300',
        'surface-container': '#1d2026',
        'surface-container-high': '#272a31',
        'primary-fixed-dim': '#d7baff',
        'on-surface': '#e1e2eb',
        'on-primary': '#411478',
        'surface-container-low': '#191c22',
        'on-secondary-fixed': '#3c0029',
        'secondary-fixed': '#ffd8e9',
        'amber-flare': '#FFB86C',
        background: '#10131a',
        'surface-variant': '#32353c',
        primary: '#d7baff',
        'tertiary-container': '#db9950',
        'void-blue': '#0B0E14',
        'on-primary-fixed-variant': '#593090',
        'surface-bright': '#363940',
        'surface-container-lowest': '#0b0e14',
        'surface-dim': '#10131a',
        'glimmer-pink': '#FF79C6',
        'on-secondary-container': '#ff92cd',
        'on-tertiary-fixed': '#2c1600',
        'nebula-purple': '#2D1B4E',
        'inverse-surface': '#e1e2eb',
        starlight: '#F8F8F2',
        error: '#ffb4ab',
        'on-secondary-fixed-variant': '#860f60',
        'on-primary-fixed': '#290055',
        'primary-fixed': '#eddcff',
        'on-error': '#690005',
        'inverse-primary': '#714aaa',
        'on-tertiary-fixed-variant': '#683c00',
        'inverse-on-surface': '#2e3037',
        'secondary-container': '#860f60',
        tertiary: '#ffb86c',
        'secondary-fixed-dim': '#ffafd7',
        'outline-variant': '#4a4451',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        'label-caps': ['BeVietnamPro', 'Noto Sans SC', 'sans-serif'],
        'headline-lg': ['Manrope', 'Noto Sans SC', 'sans-serif'],
        'body-md': ['BeVietnamPro', 'Noto Sans SC', 'sans-serif'],
        'display-aura': ['Manrope', 'Noto Sans SC', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'Noto Sans SC', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.2em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0.05em', fontWeight: '300' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '300' }],
        'display-aura': ['42px', { lineHeight: '52px', letterSpacing: '0.1em', fontWeight: '200' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '0.05em', fontWeight: '300' }],
      },
    },
  },
  plugins: [],
}
